/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `JudgeHost`;

DROP TABLE IF EXISTS `Result`;

DROP TABLE IF EXISTS `Submission`;

DROP TABLE IF EXISTS `Language`;

DROP TABLE IF EXISTS `Contest_groups`;

DROP TABLE IF EXISTS `Contest_users`;

DROP TABLE IF EXISTS `Contest_tasks`;

DROP TABLE IF EXISTS `Contest`;

DROP TABLE IF EXISTS `TestCase`;

DROP TABLE IF EXISTS `Task`;

DROP TABLE IF EXISTS `Group_users`;

DROP TABLE IF EXISTS `Group`;

DROP TABLE IF EXISTS `User`;

DROP TABLE IF EXISTS `File`;

CREATE TABLE `File` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `User` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `admin` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Group` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Group_users` (
  `object_id` INT UNSIGNED NOT NULL,
  `value` INT UNSIGNED NOT NULL,
  CONSTRAINT `Group_users_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Group` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Group_users_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `User` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Group_users` (`object_id`);

CREATE TABLE `Task` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `evaluator` INT UNSIGNED NOT NULL
  /*
  CONSTRAINT `Task_evaluator_fk`
    FOREIGN KEY (`evaluator`)
    REFERENCES `File` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `TestCase` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `task` INT UNSIGNED NOT NULL,
  `input` INT UNSIGNED NOT NULL,
  `output` INT UNSIGNED NOT NULL
  /*
  CONSTRAINT `TestCase_task_fk`
    FOREIGN KEY (`task`)
    REFERENCES `Task` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `Contest` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Contest_tasks` (
  `object_id` INT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` INT UNSIGNED NOT NULL,
  CONSTRAINT `Contest_tasks_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Contest` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Contest_tasks_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Task` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Contest_tasks` (`object_id`);

CREATE INDEX `index_i`
  ON `Contest_tasks` (`index`);

CREATE TABLE `Contest_users` (
  `object_id` INT UNSIGNED NOT NULL,
  `value` INT UNSIGNED NOT NULL,
  CONSTRAINT `Contest_users_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Contest` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Contest_users_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `User` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Contest_users` (`object_id`);

CREATE TABLE `Contest_groups` (
  `object_id` INT UNSIGNED NOT NULL,
  `value` INT UNSIGNED NOT NULL,
  CONSTRAINT `Contest_groups_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Contest` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Contest_groups_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Group` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Contest_groups` (`object_id`);

CREATE TABLE `Language` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `suffix` VARCHAR(16) NOT NULL,
  `compiler` INT UNSIGNED NOT NULL,
  `runner` INT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Submission` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user` INT UNSIGNED NOT NULL,
  `task` INT UNSIGNED NOT NULL,
  `language` INT UNSIGNED NOT NULL,
  `source` INT UNSIGNED NOT NULL,
  `binary` INT UNSIGNED NOT NULL,
  `status` INT NOT NULL
  /*
  CONSTRAINT `Submission_user_fk`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`id`)
  */
  /*
  CONSTRAINT `Submission_task_fk`
    FOREIGN KEY (`task`)
    REFERENCES `Task` (`id`)
  */
  /*
  CONSTRAINT `Submission_language_fk`
    FOREIGN KEY (`language`)
    REFERENCES `Language` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `Result` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `submission` INT UNSIGNED NULL,
  `testCase` INT UNSIGNED NULL,
  `output` INT UNSIGNED NOT NULL,
  `errOutput` INT UNSIGNED NOT NULL,
  `result` INT NOT NULL,
  `time` FLOAT NOT NULL,
  `memory` INT NOT NULL
  /*
  CONSTRAINT `Result_submission_fk`
    FOREIGN KEY (`submission`)
    REFERENCES `Submission` (`id`)
  */
  /*
  CONSTRAINT `Result_testCase_fk`
    FOREIGN KEY (`testCase`)
    REFERENCES `TestCase` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `JudgeHost` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `host` VARCHAR(255) NOT NULL)
 ENGINE=InnoDB;

